### PR TITLE
New houseprint

### PR DESCRIPTION
**Pull request by JrtPec**

### CODE REVIEW

**Comment by saroele** [comment]
Jan,
I pulled your branch and solved the conflict (was only in the .gitignore). 
I have already successfully ran the New Houseprint.ipynb notebook.  I want to merge it quickly in the mail develop branch, but I will first go to all the notebooks and make sure the conversion is fine.  

I think we should have a unittest for this new module.  I will start writing it but I'll push the develop branch first so everybody can start using this new houseprint api. 

I'll keep you posted,
Roel

**Comment by JrtPec** [comment]
It would be nice if you could set up the unit test environment and write some examples, since I have no experience with unit tests. Once I can see how it's done I will see if I can help out.

**Comment by saroele** [comment]
ok, I'll do that, can take a few days though.

**Comment by saroele** [comment]
@JrtPec 
I created a copy of the houseprint reponses for the unit and integration tests. But even after sharing it with opengridcc@gmail.com I'm unable to load this with gspread.  The error is a 'Spreadsheet not found' error.  

I supposed the json key was for opengridcc@gmail.com, but maybe it's for another account?  Or do you have any idea why it's not working? 
You can test if it works by adding `spreadsheet='unit and integration test houseprint'` to the initialization call for the Houseprint object.

**Comment by JrtPec** [comment]
You have to share the spreadsheet with te e-mailadres that is specified in the OAuth JSON :-)

**Comment by saroele** [comment]
hehe, indeed ;-)
thanks, works now.  I can move on!

**Comment by saroele** [comment]
unit (and integration) test for houseprint is well advanced.  I want to change the houseprint api a bit, i'll do that in a separate branch

**Pull request closed without merging**
