### PR TITLE
Regression analysis

### PR DESCRIPTION
**Pull request by JrtPec**
Partyparty, regression demo time

### CODE REVIEW

**Comment by Ryton** [comment]
Looking good!

One remark though: 
* Why not use degree hours and hourly (or 4 or 6 hourly) resolution instead of degree days? That will get you much more points on the graphs and thus a better (more reliable/consistent) energy signature / regression fit. 

Opengrid is quite unique in having sub-daily data, so we better make full use of it!

**Comment by JrtPec** [comment]
That's the point! This is an exact port of the code that is already implemented on EnergyID, so using it as-is wouldn't be adding much value. We should try and see if we can draw useful conclusions from weekly, daily, hourly data... try to use different independent variables etc.

Do you have a formula for degree hours? I'd like to implement that.

**Comment by saroele** [comment]
I think going to sub-daily regression is no free lunch.  Dynamic effects come into play, and your simple linear model will not work anymore.  A dynamic model (eg. RC analogy) is needed. 

I think we can still do a lot on daily/weekly resolution before we move to dynamic models.

**Comment by Ryton** [comment]
I constructively disagree, @saroele . ;-)

I do agree that, when naively going to below daily level (e.g. to hourly), new dynamics should be considered, but even now, at daily level you'll have non-modeled weekday vs weekend dynamics (in setpoints/comfort, domestic hot water usage, etc).

But, by grouping by well-chosen, sub-daily periods instead, e.g.:
*  night, eve & morning, 
* weekday (assumed unoccupied), 
* weekend during the day, 
you will (should) have less thermal dynamics within each group (with minimal timeblocks of 4-6 hrs), compared to the daily splitup, as the dominant control dynamics should be (i think) all within than this grouping.

Weekly / daily could be interesting as an exercise and input towards EnergyID, but my personal interest/focus is on the smaller timescale.

But no worries, feel free follow your heart & nose, we'll see where it leads us :-)

**Comment by Ryton** [comment]
There's a whole paper on how to apply degree hours in the url below. The formula you want is on p3
http://amet-me.mnsu.edu/UserFilesShared/SolarWall/Degree%20Day%20Analysis/An%20application%20of%20the%20degree-hours%20method%20to%20estimate%20the%20residential%20heating%20energy%20requirement%20and%20fuel%20consumption%20in%20Istanbul%20-%20Durmayaz,%20Kadioglu%20and%20Sen.pdf

It's basically the same as degree days (using historic mean day temperature as a reference), but split up per hour instead.

**Comment by Ryton** [comment]
@saroele  
i failed to prove you wrong and therefore, QED, you are proven right (until further notice)! :-P

Based on some quick hacks with available data & degree hours/days, the resulting point clouds indeed shows quite a lot of variation, even when using 'just' daily averaged data. 

Therefore, a weekly or half-weekly consumption of heat generation equipment is probably a safer way to generate robust, non-supervised energy signatures.

**Pull request merged**
