### PR TITLE
Issue8 fastsync

### PR DESCRIPTION
**Pull request by kdebrab**
This speeds up the synchronization significantly. The speed up is realized by storing the data in hdf files instead of csv files. See #8.

The following new functions have been defined in fluksoapi:
* save_file
* load_file
* load_sensor

The following functions have been removed from fluksoapi:
* ~~pull_api (not used/needed anymore?)~~
* ~~parse (not used/needed anymore?)~~
* find_csv (functionally equivalent with consolidate_sensor, use ´´load_sensor(...)´´ instead of ´´load_csv(find_csv(...))´´)
* load_csv (replaced by the more generic load_file)
* save_csv (replaced by the more generic save_file)

Before merging, we should agree on the above, or alternatively revert some changes and/or make additional changes. I think I may have been overactive in removing functions, so please react if you believe I was and I'll revert those functions.

### CODE REVIEW

**Comment by kdebrab** [comment]
Maybe we should also clean up some old scripts.

When checking for broken functionality I found the following (no longer maintained?) scripts. Most of them are quite old and return errors when executing them even without the changes of this branch. I think we should either maintain or remove them if we think they are no longer useful:
* extract_flukso_api.py (the only script actually using pull_api and parse + uses save_csv)
* job_serve_monitoring_data.py (not working as consolidate does not exist anymore)
* load_duration.py (idem + uses load_csv)
* time_conversion_and_consolidation.py (idem + uses load_csv and save_csv)
* time_conversion_and_daily_consolidation.py (idem + uses load_csv and save_csv)
* split_csv_by_day.py (idem + uses load_csv and save_csv)

**Comment by saroele** [comment]
Karel,

I have not yet looked at your changes in detail.  Just bear in mind that
some of these scripts and library functionality is currently used on the
droplet.  For example to pull the data from the fluksoapi and create the
csv files that are served on the private webserver.  It looks a bit like
you turn the logic around: first changing the api, and then you would
delete all code that won't work anymore because it uses the old api :-)

I like your attempts to get a quicker sync, but we shouldn't forget to keep
the current functionality on the droplet.

For one-time operations I had indeed created some scripts that are not
needed anymore.
Roel

**Comment by kdebrab** [comment]
The scripts I proposed to (maybe) delete didn't work already before the changes I made. Of course, if they are still useful, we should adapt them, not delete them. All other things work as they did before (e.g. all ipython notebooks), as most of the high-level api did not change.

I don't know what you mean with the droplet though. Where can I find it?

**Comment by kdebrab** [comment]
I think I start to understand. Withe the droplets you mean the job-scripts running somewhere in a crontab. I'll make sure that functionality is not broken!

**Comment by saroele** [comment]
yes, indeed.  The droplet is the virtual machine, hosted by digital ocean.
(They call each vm a droplet, ... ocean, get it?) :-)

So far, only a few people have access to that machine: Bart, Wouter, myself
and Dirk I think.  It is used to run a few cron jobs:
- extract all data from opengrid flukso's from the flukso server
- compact data to a .zip file per day with one csv/sensor
- create an anonymous copy of the houseprint every day
- put this zip and the houseprint on our private webserver, where our sync
scripts go get it.

Here are the crontab entries:
0 */8 * * * cd /usr/local/data; python
/usr/local/src/opengrid/scripts/extract_flukso_api.py
*/5 * * * * cd /usr/local/data; python
/usr/local/src/opengrid/scripts/job_SyncAndRenderGraphs.py
20 1 * * * cd /usr/local/data; python
/usr/local/src/opengrid/scripts/job_serve_monitoring_data.py

The SyncAndRenderGraphs job was created during the sprint, it is supposed
to be extended with analysis scripts.
I hope this clarifies a few things.  Thanks for ensuring this functionality
in your pull request!!

**Comment by Ryton** [comment]
As already discussed some other issue, a while ago (but cannot find it atm):
a line in fluksoapi.py (line266): sensor_set = {x.split('_')[1] for x in glob.glob(os.path.join(folder, '*'))} 
gives issues if you have folder names which also include "_ " :'(
sensor_set = {x.split('_')[-5] for x in glob.glob(os.path.join(folder, '*'))} works for me. Is it worth committing this change, or should I just refrain from labeling my folders with leading underscores ("_L_foldername\") ? :-)  

Orgininal response:
>>fluksoapi.synchronize(path_to_data)
"About to combine 1564 files for sensor L " (1zip file, ~255 csv files, and lots of tmpo files)
Answer: Memory error

Response with  "sensor_set = {x.split('_')[-7] ..."
About to consolidate 68 sensors
About to combine 19 files for sensor b325dbc1a0d62c99a50609e919b9ea06
>> thus, ok

**Pull request merged**
