### PR TITLE
Dockerizing opengrid

### PR DESCRIPTION
**Pull request by wouterh**
Not yet thoroughly tested :-)

### CODE REVIEW

**Comment by wouterh** [comment]
missing something for the houseprint

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-bb3aea258b46> in <module>()
      5 script_dir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
      6 sys.path.append(os.path.join(script_dir, os.pardir, os.pardir))
----> 7 from opengrid.library import houseprint
      8 from opengrid.library import config
      9 c=config.Config()

/usr/local/opengrid/opengrid/library/houseprint.py in <module>()
     17 import config
     18 import json
---> 19 from oauth2client.client import SignedJwtAssertionCredentials
     20 
     21 c = config.Config()

ImportError: No module named oauth2client.client
```

**Comment by saroele** [comment]
Nice!  Looks fairly easy, once you know how dockerfiles work....  Unfortunately, I have a corrupt docker on my laptop, should reinstall but didn't do it yet.  

Questions:
- what is your intented use case?  Running notebooks interactively by navigating to the port of the container?  Or launching a container for every python script to be executed and then shutting it down?
- you make the content of opengrid available within the container with the VOLUME directive and then mounting it to $PWD/..  This means that everything is available within the container and when writing something to that volume, it is available on the host after shutting down the container.  Right?
- It looks like we're having RAM issues on the droplet.  Would this be different when using docker you think?

I'll fix my docker problems and test one of these.
roel

**Comment by wouterh** [comment]
My main use case is for developing on a mac. I had quite some trouble installing all required dependencies on my mac at home. So for my new macbook, I chose the docker path :-)

In 'production', I wouldn't mount the code from outside the container, but include it in the container image. That's future work though... (even the development use case doesn't work entirely yet)

**Comment by saroele** [comment]
Maybe it's way easier to use the ipython/scipyserver image and build upon that.  See https://registry.hub.docker.com/u/ipython/scipyserver/

**Comment by saroele** [comment]
docker is still growing on me.   I'll free some time in the near future to work on this branch.  Are you still motivated to contribute @wouterh ?

**Comment by wouterh** [comment]
@saroele yes, but I'm very short on time lately :frowning:

**Comment by wouterh** [comment]
@saroele: Should be more or less usable now.

Steps:
* Install docker
* ./docker-build-dev.sh
* ./docker-run-dev.sh

Notebook kernel should be running at http://IP-OF-DOCKER-MACHINE:8888/
(IP-OF-DOCKER-MACHINE should be localhost on a linux with a local docker install)

**Pull request merged**
