### PR TITLE
Issue105 belpex

### PR DESCRIPTION
**Pull request by JrtPec**
#105. Pretty simple web scraper. Enter dates, get values. Demo included.

### CODE REVIEW

**Comment by saroele** [comment]
Hey Jan,

looks like a nice little addon.  Now find some useful analysis for it.  Maybe in combination with PV we can check correlations of production and belplex prices.  Interesting for research on market dynamics etc, but for opengrid we have to find some more practical use.  

But first we have to get it running :-( I get the following error when I run your notebook:
```
KeyError                                  Traceback (most recent call last)
<ipython-input-5-06ae78b383b3> in <module>()
----> 1 ts = get_belpex(start=start)

/mnt/data/work/opengrid/code/opengrid/opengrid/library/belpex.pyc in get_belpex(start, end)
     25     # Prices are fetched per day, so we'll create a set of days, download seperate dataframes per day and put them
     26     # together
---> 27     series = [get_belpex_day(date) for date in dayset(start, end)]
     28     return pd.concat(series)
     29 

/mnt/data/work/opengrid/code/opengrid/opengrid/library/belpex.pyc in get_belpex_day(date)
     44     html = fetch_website(date)
     45     # parse html into an array of timestamps and values
---> 46     index, data = parse_html(html)
     47     series = pd.Series(index=index, data=data)
     48     series = series.tz_convert('Europe/Brussels')

/mnt/data/work/opengrid/code/opengrid/opengrid/library/belpex.pyc in parse_html(html)
    101         # There is a iso8601 timestamp somewhere in an 'onclick' JavaScript call...
    102         # Luckily all arguments passed are of constant width so we can grab the stamp by index
--> 103         date = iso8601.parse_date(span['onclick'][128:152])
    104         index.append(date)
    105         # the value is right in the middle of the span

/usr/local/lib/python2.7/dist-packages/beautifulsoup4-4.3.2-py2.7.egg/bs4/element.pyc in __getitem__(self, key)
    903         """tag[key] returns the value of the 'key' attribute for the tag,
    904         and throws an exception if it's not there."""
--> 905         return self.attrs[key]
    906 
    907     def __iter__(self):

KeyError: 'onclick'

```

Any idea what I'm doing wrong?

Related to this: I'd like to be more strict on testing.  So we should try to have a small unittest (even if it's just one or two tests, at least that would test if imports work and methods run fine).  And I'd love to find a quick solution to run our notebooks in the test suite.  Just running them all to see if they reach the end.  That would be a very useful test and would cover partly the missing unittests.

**Comment by JrtPec** [comment]
Haha this is great, thanks for testing the code in the _morning_, that's right.

What happens is that every day, Belpex prices for the next day are bid upon and published, so we can look them up _24h in advance_. When I implemented it yesterday evening, I could indeed do a lookup for the day after and get valid results, so I wrote the code to default to _tomorrow_.

Right now however, the results for tomorrow haven't been published yet... (I expect them to be published before noon). I'll add some error catching :-)

You can work around this issue right now by passing `end = dt.date.today()` or some earlier date.

This really was an implementation from the viewpoint 'How quickly can I write a functional web scraper'. So it is not at all bug proof, or catching errors of any sort.

On the note of unit tests: I have been putting off learning those for far too long, so I'll try to make that my next _thing_.

**Comment by JrtPec** [comment]
Should be fixed.

**Comment by saroele** [comment]
Fixed indeed. 
AFAIK, belpex bids (for next day) have to be closed by 14h on the current day.  So shortly after 14h the market is cleared and prices are known for the entire next day.  Try-except is the perfect solution for this situation :-)

**Pull request merged**
