### PR TITLE
solar irradiance model

### PR DESCRIPTION
**Pull request by JrtPec**
Module that tracks the position of the sun for a given location and time and calculates the solar irradiance.

### CODE REVIEW

**Comment by JrtPec** [comment]
@rubenbaetens I have changed the methods so they all take SI-units as in and outputs

**Comment by rubenbaetens** [comment]
Perfect, that avoids possible confusion.

**Comment by JrtPec** [comment]
@rubenbaetens @saroele I have added a model that simulates ideal PV installations

**Comment by saroele** [comment]
Productive evening jan :-)
As we have a PV expert on board, maybe @kdebrab can have a look?

**Comment by saroele** [comment]
Don't worry about the Travis CI error: I did not yet configure it, just created an account and added opengrid. I have to dig in further in the coming days.

**Comment by saroele** [comment]
@kdebrab ga je hier naar kunnen kijken? We werken het best af in deze branch voor we mergen in de develop. Alvast bedankt

**Comment by saroele** [comment]
Some ex-colleagues from KU Leuven have created a similar script for getting solar radiation (diffuse and direct components) from cloud cover only.  @Ryton took initiative to ask them permission to use their code in opengrid.  If they agree I propose to compare both approaches and come to a single solution.

**Comment by saroele** [comment]
KU Leuven colleagues agreed to use their code and include it or rework it into opengrid. 
Lets put this on the agenda for next meeting.

**Pull request merged**
